shellspec/shellspec

docs/references.md, lib/core/matchers/be/stat.sh, sample/spec/11.matcher_spec.sh, spec/core/matchers/be/stat_spec.sh, spec/libexec/translator_spec.sh, spec/support/fixture_stat_task.sh
=> Fixed typo in matcher name

lib/bootstrap.sh, shellspec
=> Self executing specfile

install.sh, spec/install_spec.sh
=> Fixes installer fails when not exists /dev/tty even specified yes option

lib/core/dsl.sh, lib/core/hook.sh, lib/libexec/translator.sh, libexec/shellspec-translate.sh, spec/core/dsl/before_after_all_spec.sh, spec/core/dsl_spec.sh, spec/core/hook_spec.sh, spec/libexec/translator_spec.sh
=> Fixes BeforeAll / AfterAll to share states

lib/core/dsl.sh, lib/core/matchers/satisfy.sh, lib/core/modifiers/result.sh, lib/core/output.sh, lib/core/outputs.sh, lib/libexec/grammar/dsls, spec/core/dsl/assert_spec.sh, spec/core/dsl_spec.sh, spec/core/matchers/satisfy_spec.sh, spec/core/modifiers/result_spec.sh
=> Implement Assert expectation

docs/architecture.md, lib/core/dsl.sh, lib/core/hook.sh, lib/general.sh, lib/libexec/grammar.sh, lib/libexec/grammar/dsls, lib/libexec/translator.sh, libexec/shellspec-translate.sh, shellspec, spec/core/dsl/mock_spec.sh, spec/core/dsl_spec.sh, spec/libexec/translator_spec.sh, spec/spec_helper.sh
=> Command based mock

docs/reporter.md, lib/core/dsl.sh, lib/core/output.sh, lib/core/outputs.sh, lib/general.sh, lib/libexec/reporter/color_schema.sh, lib/libexec/reporter/conclusion_formatter.sh, lib/libexec/reporter/debug_formatter.sh, lib/libexec/reporter/documentation_formatter.sh, lib/libexec/reporter/failures_formatter.sh, lib/libexec/reporter/finished_formatter.sh, lib/libexec/reporter/junit_formatter.sh, lib/libexec/reporter/kcov_formatter.sh, lib/libexec/reporter/methods_formatter.sh, lib/libexec/reporter/profiler_formatter.sh, lib/libexec/reporter/progress_formatter.sh, lib/libexec/reporter/references_formatter.sh, lib/libexec/reporter/summary_formatter.sh, lib/libexec/reporter/tap_formatter.sh, libexec/shellspec-reporter.sh, spec/core/dsl_spec.sh, spec/core/hook_spec.sh, spec/core/output_spec.sh
=> Improve error handling for BeforeAll/AfterAll hooks

.travis.yml, lib/getoptions.sh, lib/getoptions_help.sh, lib/libexec/optparser.sh, libexec/shellspec-runner.sh, package.json, shellspec, spec/getoptions_help_spec.sh, spec/getoptions_spec.sh, spec/libexec/optparser_spec.sh
=> Replace option parsing with getoptions

README.md, lib/core/outputs.sh
Sorry for a large diff, but I couldn't find a logical way to slice it into smaller change sets
=> contribution to issue #87 improve documentation

docs/reporter.md, lib/core/outputs.sh, lib/libexec/reporter.sh, lib/libexec/reporter/junit_formatter.sh, libexec/shellspec-reporter.sh, spec/libexec/reporter_spec.sh
=> Fill <system-out> and <system-err> in jUnit XML

lib/general.sh, lib/libexec/reporter/profiler_formatter.sh, lib/libexec/shellspec.sh, shellspec, spec/general_spec.sh, spec/libexec/shellspec_spec.sh
=> Allow run the tests from any subdirectory

docs/references.md
Please check if I didn't break the intended meaning
=> Few further language improvements in the docs

lib/libexec/optparser/optparser.sh, lib/libexec/optparser/parser_definition.sh, lib/libexec/optparser/parser_definition_generated.sh, spec/libexec/optparser/optparser_spec.sh
=> Make deprecation for  -D option

lib/libexec/optparser/parser_definition.sh, lib/libexec/optparser/parser_definition_generated.sh, lib/libexec/shellspec.sh, shellspec, spec/libexec/shellspec_spec.sh
=> Add path syntax to match recursive directories

lib/libexec/shellspec.sh, shellspec, spec/libexec/shellspec_spec.sh
=> Deprecate $HOME/.shellspec

CHANGELOG.md, shellspec
=> Fixed a bug when specified relative tmp directory path

helper/ksh_workaround.sh, helper/spec_helper.sh, lib/core/evaluation.sh, lib/core/modifiers/result.sh, lib/core/outputs.sh, lib/core/subjects/line.sh, lib/core/subjects/stderr.sh, lib/core/subjects/stdout.sh, lib/core/subjects/word.sh, spec/core/outputs_spec.sh, spec/core/subjects/stderr_spec.sh, spec/core/subjects/stdout_spec.sh
=> Improve performance when stdout and stderr are not validated

spec/core/dsl_spec.sh
=> Fix typo in dsl_spec.sh

spec/general_spec.sh
=> Fix typo in general_spec.sh

README.md
Some links, formatting, grammar/spelling fixes, and minor rewrites for clarity
=> README.md: assorted proofreading

README.md
Great fan of your software :heart_eyes: 
Here's only a minor thing I was struggling with that I think could be added to the README.md
=> README.md: extend hooks section

lib/core/dsl.sh, spec/core/evaluation_spec.sh
Relates to https://github.com/shellspec/shellspec/issues/178
=> ISSUE-178 allow "When I..." evaluation

README.md, docs/test.md
Found some typos in the documents, so I fixed them.
=> fix typo in documents

README.md
For those of us in the unknown, like me
=> README: Adds link explaining what BDD means
