- lib/core/evaluation.sh
- spec/core/evaluation_spec.sh
I discovered this when I was testing a function which is of the form;
```sh
func() {
_err=${?}
...[stuff here]...
return ${_err}
}
```
...and I was expecting it to return true (`The status should be success`), but I found that `shellspec_evaluation_call` was always calling the function with `${?}` already set to non-zero. It turns out it is a leftover of the non-empty ("-n") test of `${SHELLSPEC_DATA}` just before the evaluation, so I added the noop `:` to ensure that never happens. If you don't like the aesthetics of a lone ":" on a line by itself it could instead be `true`, as I guess that is usually just aliased to `:` anyway...
> Ensure eval starts with errno zero

- README.md
Add instructions to install _shellspec_ using the available ArchLinux package from the AUR.
The new section should be used to document installation of packages from other Linux distribution when they will be available.
> Document the available ArchLinux package

- lib/core/evaluation.sh
- spec/core/evaluation_spec.sh
- spec/spec_helper.sh
> Ensures "no pipe" and "terminal" in evaluation

- lib/core/outputs.sh
- spec/core/evaluation_spec.sh
- spec/core/matchers/include_spec.sh
- spec/core/modifiers/contents_spec.sh
- spec/core/modifiers/line_spec.sh
- spec/core/modifiers/lines_spec.sh
- spec/core/modifiers/word_spec.sh
- spec/core/subjects/stderr_spec.sh
- spec/core/subjects/stdout_spec.sh
- spec/core/subjects/variable_spec.sh
- spec/core/utils_spec.sh
- spec/general_spec.sh
- spec/spec_helper.sh
Shellspec failed unexpectedly due to using LF in specfile.
Fixes #31
> Remove LF and TAB in specfile

- README.md
- shellspec
Note: Kcov v35 or later is required to enable coverage.
Close #23
> Improve kcov version detection (v35 or later is required)

- lib/core/matchers/match.sh
- lib/general.sh
- lib/libexec/translator.sh
- spec/core/matchers/match_spec.sh
- spec/general_spec.sh
- `match` matcher deprecated, use `match pattern` matcher instead
- Fix --example option
Fixes #28
> Add new match pattern matcher

- lib/core/modifiers/result.sh
- lib/core/utils.sh
- spec/core/modifiers/result_spec.sh
- Add function name check 
- Pass stdout, stderr, status as arguments
result examples
```sh
get_version() {
echo "$1" | grep -o '[0-9.]*' | head -1
}
When call echo "GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)"
The result of function get_version should equal "4.4.20"
The result of "get_version()" should equal "4.4.20" # shorthand
```
Fixes #30
> Improve result modifier

- lib/core/matchers/satisfy.sh
- lib/core/outputs.sh
- lib/core/utils.sh
- sample/spec/11.matcher_spec.sh
- spec/core/matchers/satisfy_spec.sh
- Add function name check
- The subject is stored in the same variable name as the function name
satisfy examples
```sh
value() {
test "${value:?}" "$1" "$2"
}
formula() {
value=${fomula:?}
[ $(($1)) -eq 1 ]
}
When call echo "50"
The output should satisfy value -gt 10
The output should satisfy formula "10 <= value && value <= 100"
```
> Improve satisfy matcher

- install.sh
- lib/libexec/shellspec.sh
- shellspec
- spec/libexec/shellspec_spec.sh
- install.sh: Install to under $HOME/.local by default  
- Use $HOME/.config if not defined XDG_CONFIG_HOME
Close #24
> Fix XDG base directory supporting

- .gitattributes
- lib/libexec/translator.sh
- spec/fixture/specfile-crlf.txt
- spec/fixture/specfile-lf.txt
- spec/libexec/translator_spec.sh
> Support windows line endings for specfiles

- lib/core/dsl.sh
- lib/core/evaluation.sh
- lib/general.sh
Shell that fails without workaround
- bash 4.1.2, 4.1.5
- bash 4.2.37, 4.2.46, 4.2.53
- bash 4.3.30, 4.3.42, bash 4.3.43
- posh 0.8.5. 0.12.3, 0.12.6, 0.13.1, 0.13.2
- mksh-39, 40
- pdksh 5.2.14
Shell that fails with workaround on dsl.sh.
- bash 4.1.2, 4.1.5
- bash 4.2.37, 4.2.46, 4.2.53
- bash 4.3.30, 4.3.42, bash 4.3.43
- ~~posh 0.8.5. 0.12.3, 0.12.6, 0.13.1, 0.13.2~~
- ~~mksh-39, 40~~
- ~~pdksh 5.2.14~~
Shell that fails with workaround on dsl.sh + evaluation.sh.
- ~~bash 4.1.2, 4.1.5~~
- ~~bash 4.2.37, 4.2.46, 4.2.53~~
- bash 4.3.30, 4.3.42, bash 4.3.43
- ~~posh 0.8.5. 0.12.3, 0.12.6, 0.13.1, 0.13.2~~
- ~~mksh-39, 40~~
- ~~pdksh 5.2.14~~
All fixed with workaround on dsl.sh + evaluation.sh + general.sh.
> errexit workaround

- lib/core/dsl.sh
- lib/core/evaluation.sh
- lib/libexec/grammar.sh
- lib/libexec/translator.sh
- libexec/shellspec-translate.sh
- spec/core/dsl/parameters_spec.sh
- spec/core/dsl_spec.sh
- spec/core/evaluation_spec.sh
- spec/libexec/translator_spec.sh
Improvement
- Support  `Parameters` with `Data` helper.
Change
-  To avoid typo, Comments in the `Data` helper only accept those starts with  `#<space>` not `#`.
Close #57
> Improve data helper

- libexec/shellspec-translate.sh
This checks if the file descriptor 1 is available, which is standard output.
Fixes #66
> /dev/tty may exist, but not be writable.

- Makefile
- lib/core/dsl.sh
- lib/libexec/optparser/parser_definition.sh
- lib/libexec/optparser/parser_definition_generated.sh
- libexec/shellspec-translate.sh
- spec/core/dsl_spec.sh
Rename the option because their usage and meaning are different from those of tar or git's `-C` option.
NOTE: This option exists only in the master branch and has not yet been released.
> Replace -C, --directory option to --execdir option

- docs/references.md
@ko1nksm minor edits:
- fix discussed https://github.com/shellspec/shellspec/issues/158
- fix `word` example
- minor grammatical suggestions https://github.com/shellspec/shellspec/issues/87
ヨロピク〜
> Minor improvements to docs

- CHANGELOG.md
- README.md
- docs/directory_structure.md
- docs/references.md
- helper/ksh_workaround.sh
Add documentation on the following changes:
- #135 Allow run the tests from any subdirectory
- #146 Replace -C, --directory option to --execdir option (#137 Add -C, --directory option)
> Improving documentation for 0.28.0

- helper/fixture/test_when_run_source
- lib/core/evaluation.sh
- spec/core/evaluation_spec.sh
> Fix a bug that test command cannot redefine when using "when run source"

- docs/references.md
Hi,
I found miss type in the document (https://github.com/shellspec/shellspec/blob/master/docs/references.md).
ex:
* wrong: The `outout` should equal <STRING> -> correct: The `output` should equal <STRING>
Please confirm.
Regards.
Yohei
> Fixed miss type for string-matchers document

- libexec/shellspec-inspection.sh
Remove the workaround as the problem has been resolved [here](https://github.com/cirruslabs/cirrus-ci-agent/pull/98).
> Remove workaround for CirrusCI

- .github/workflows/windows-busybox.yml
This is due to a bug in the upstream BusyBox.
https://bugs.busybox.net/show_bug.cgi?id=14061
> Avoid broken BusyBox-w32 4264.0

- README.md
- docs/references.md
- examples/spec/11.matcher_spec.sh
- lib/core/matchers.sh
- lib/core/matchers/be/stat.sh
- lib/core/matchers/exist.sh
- package.json
- spec/core/matchers/be/stat_spec.sh
- spec/install_spec.sh
- spec/libexec/runner_spec.sh
- spec/shellspec-gen-bin_spec.sh
Continuing where https://github.com/shellspec/shellspec/pull/220 left off.
Relates to discussion https://github.com/shellspec/shellspec/discussions/221
----
Disclaimer: **I'm not 100% sure what I'm doing in all cases here.**   
My implementation is mostly copy-paste-adjust, I don't understand the big picture as well as I like, yet.  
Here's hoping I can still fix all test cases.
----
**Draft status:** 
<details>
```
$ TARGET=bash ./contrib/all.sh ./shellspec
----------------------------------------------------------------------------
Running: /usr/bin/bash [bash 5.1.4(1)-release]
..................................................................................................................................................................................................................... …
```
> More fluent exist matcher

- lib/libexec/reporter.sh
The **`--profiler` option** now works on locales which had the decimal separator set as comma (`,`) and not period (`.`), such as **Italian, Spanish, French** and many others.
See [my answers](https://github.com/shellspec/shellspec/issues/274#issuecomment-1311636524) on issue #274 for more info on the subject.
@ko1nksm This shouldn't be a problem, but i could test this solution **only** on **Bash**. 
It would be great if you could run the tests for the other shells too. 😃
> fix: Added support for comma (`,`) as decimal separator - Fix #274

- lib/core/evaluation.sh
- spec/core/evaluation_spec.sh
This commit tries to fix `When run script` evaluation for scripts having spaces between `#!` and the command in their shebang, e.g. `#! /usr/bin/env bash`.
This commit also updates the associated unit test.
Indeed, the `shellspec_shebang_arguments()` function has not been trying to trim these spaces before.
---
I've tried to respect coding conventions, but I'm not sure about the quality of the result and wait for reviews.
> lib/core/evaluation.sh: trim spaces between `#!` and the command
